# Generated by Django 3.1.5 on 2021-01-15 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20210114_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviecast',
            name='cast',
        ),
        migrations.RemoveField(
            model_name='moviecast',
            name='mainsub',
        ),
        migrations.RemoveField(
            model_name='moviecast',
            name='movie',
        ),
        migrations.DeleteModel(
            name='Cast',
        ),
        migrations.DeleteModel(
            name='MainSub',
        ),
        migrations.DeleteModel(
            name='MovieCast',
        ),
    ]
